name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build (Test)
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build (Release)
      if: github.ref_type == 'tag'
      run: cargo build --verbose --release
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
          files: ./target/release/${{ github.event.repository.name }}
